config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'articles#index'

  resources :articles
  resources :pages

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  post 'articles#new_comment' => 'articles#new_comment'
  get 'articles#destroy_comment' => 'articles#destroy_comment'


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord

  validates :name, :title, :body, presence: true


end

app/models/user.rb
class User < ApplicationRecord



    validates :name, :email, presence: true
    validates :email, uniqueness: true
    has_secure_password
    validates :password, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:uid]) if session[:uid]
  end
  helper_method :is_admin?
  def is_admin?
    return current_user.name == 'administrator'
  end

  def authorize
    redirect_to '/login' unless current_user
  end
  def authorize_admin
    redirect_to '/' unless current_user and current_user.name == 'administrator'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorize, except: [:show, :index]

  def new

  end

  def create
    if (params[:article][:id] != '')
      article = Article.find(params[:article][:id])
      if  article.poster_id != current_user.id
        flash[:error] = 'You can not edit not your posts'
        return redirect_to '/'
      end

      article.update_attributes(article_params)
      flash[:success] = 'Post updated'
      return redirect_to article
    end

    @article = Article.new(article_params)
    @article.date = DateTime.now
    @article.poster_id = current_user.id

    @article.save
    flash[:success] = "Post created"
    redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
    @comments = Comment.where(:post_id => @article.id)
  end

  def index
    @articles = Article.all;
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.poster_id = current_user.id
      if @article.destroy
        flash[:success] = "Post deleted"
        return redirect_to articles_path
      end
      flash[:error] = "Could not delete post"
      return redirect_to articles_path
    else
      flash[:error] = "You can not delete that article"

    end
    redirect_to articles_path

  end

  def edit
    @article = Article.find(params[:id])
    render 'new'
  end

  def new_comment
    nComment = Comment.new(comment_params)
    nComment.save
    redirect_to Article.find(nComment.post_id)
  end

  def destroy_comment
    comment_to_delete = Comment.find(params[:id])
    if current_user.id == comment_to_delete.user_id
      comment_to_delete.destroy
    end
    article = Article.find(comment_to_delete.post_id)
    redirect_to article
  end


  private
  def article_params
    return params.require(:article).permit(:title, :text)
  end

  def comment_params
    return params.require(:new_comment).permit(:text, :user_id, :post_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authorize_admin, except: [:show]
  def new

  end

  def create
    @page = Page.new(page_params)
    if @page.save
      flash[:success] = 'Created new page'
      return redirect_to @page
    end
    flash[:error] = 'Could not save'
    redirect_to '/'
  end

  def show
    @page = Page.find(params[:id])
  end

  def index
    @pages = Page.all
  end

  def edit
    @new_page = Page.find(params[:id])
    render 'new'
  end
  def update
    p = Page.find(params[:id])
    p.update_attributes page_params
    redirect_to p
  end

  def destroy
    p = Page.find(params[:id])
    p.destroy
    redirect_to pages_path
  end


private
  def page_params
    params.require(:new_page).permit(:body, :name, :title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        if(current_user != nil)
            redirect_to '/'
        end
    end
    
    def create
        user = User.find_by_email(params[:user][:email])
        if user && user.authenticate(params[:user][:password])
            session[:uid] = user.id
            redirect_to '/'
        else
            redirect_to '/login'
        end
        
    end
    
    def destroy
        session[:uid] = nil
        redirect_to '/login'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  def new
    current_user
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:uid] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    flash_type = flash_type.to_sym()
    {success: "alert-success", error: "alert-danger", warning: "alert-warning", notice: "alert-info"}[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible fade in") do
        concat content_tag(:button, 'x', class: "close", data: {dismiss: 'alert'})
        concat message
      end)
    end
    nil
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<h2>All articles</h2>

<% @articles.each do |article| %>

    <div class="jumbotron">
      <h2>
        <%= article.title %>
      </h2>
      <hr \>
      <p>
        <%= truncate article.text.html_safe, length: 256 %>
      <hr \>
      <div class="row pull-right">
        <%= link_to 'Show post', {action: :show, id: article.id}, method: :get, class: "btn btn-primary" %>
        <% if current_user && article.poster_id == current_user.id %>
            <%= link_to 'Edit post', {action: :edit, id: article.id}, method: :get, class: "btn btn-primary" %>
            <%= link_to 'Delete post', {action: :destroy, id: article.id}, method: :delete, data: {confirm: 'You sure?'}, class: "btn btn-primary" %>
        <% end %>
      </div>
      </p>
    </div>
<% end %>

app/views/articles/new.html.erb
<%= form_for( :article, url: articles_path, class: "form-horizontal" ) do |f| %>
    <fieldset>
        <legend>Add article</legend>
        <div class="form-group">
            <%= f.label :id, class: "col-lg-2 control-label" %>
                <div class="col-lg-10">
                    <%= f.text_field :id, class: "form-control", readonly: 'true' %>
                </div>
        </div>
        <div class="form-group">
            <%= f.label :title, class: "col-lg-2 control-label" %>
                <div class="col-lg-10">
                    <%= f.text_field :title, class: "form-control" %>
                </div>
        </div>
        <div class="form-group">

            <%= f.label :text, class: "col-lg-2 control-label" %><br />
                <div class="col-lg-10">
                    <%= f.text_area :text, class: "form-control wysihtml5" %>
                </div>
        </div>
        <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
                <%= f.submit "Save", class: "btn btn-default" %>
            </div>
        </div>
    </fieldset>
    <% end %>

app/views/articles/show.html.erb
<div class="article-header">
  <h1><%= @article.title.html_safe %></h1>
  <hr \>
</div>
<div class="article-created"><%= @article.created_at %></div>
<div class="article-body">
  <%= @article.text.html_safe %>
</div>

<% unless @comments.empty? %>
    <div class="row">
      <div class="col-lg-offset-1">
        <h2>Comments:</h2>
      </div>
    </div>
<% end %>

<% @comments.each do |comment| %>
    <div class="row">
      <div class="col-sm-1">
      </div><!-- /col-sm-1 -->
      <div class="col-sm-5">
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong><%= User.find(comment.user_id).name %></strong>
            <span class="text-muted"><%= distance_of_time_in_words_to_now(comment.created_at) %></span>
            <% if current_user && current_user.id == comment.user_id %>
                <span class="pull-right"><%= link_to 'X', action: 'destroy_comment', :id => comment.id %></span>
            <% end %>Comm
          </div>
          <div class="panel-body">
            <%= comment.text %>
          </div><!-- /panel-body -->
        </div><!-- /panel panel-default -->
      </div><!-- /col-sm-5 -->
    </div>
<% end %>

<% if current_user %>

    <%= form_for :new_comment, url: {action: 'new_comment'}, html: {class: "form-horizontal col-lg-8 col-lg-offset-0"} do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :post_id, :value => @article.id %>
        <fieldset>
          <legend>Add comment</legend>
          <div class="form-group">
            <label for="textArea" class="col-lg-2 control-label">Comment:</label>
            <div class="col-lg-10">
              <%= f.text_area :text, class: 'form-control', rows: 5 %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </fieldset>
        </>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>WebBlog in Rails</title>
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'shared/navigation' %>
    <div class="container">
      <%= flash_messages %>

      <%= yield %>
    </div>
</body>

</html>

app/views/pages/edit.html.erb
<%= form_for( :new_page, url: edit_page_path, class: "form-horizontal", method: :patch ) do |f| %>
    <fieldset>
      <legend>Add page</legend>
      <div class="form-group">
        <%= f.label :name, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :title, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">

        <%= f.label :body, class: "col-lg-2 control-label" %><br />
        <div class="col-lg-10">
          <%= f.text_area :body, class: "form-control wysihtml5" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit "Save", class: "btn btn-default" %>
        </div>
      </div>
    </fieldset>
<% end %>

app/views/pages/index.html.erb
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>#</th>
    <th>Page name</th>
    <th>Page title</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
  </thead>
  <tbody>
  <% @pages.each do |page| %>
      <tr>
        <td><%= page.id %></td>
        <td><%= page.name %></td>
        <td><%= page.title %></td>
        <td><%= link_to 'Edit', {action: :edit, id: page.id}, method: :get %></td>
        <td><%= link_to 'Delete', {action: :destroy, id: page.id}, method: :delete %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/pages/new.html.erb
<%= form_for( :new_page, url: pages_path, class: "form-horizontal" ) do |f| %>
    <fieldset>
      <legend>Add page</legend>
      <div class="form-group">
        <%= f.label :name, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :title, class: "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">

        <%= f.label :body, class: "col-lg-2 control-label" %><br />
        <div class="col-lg-10">
          <%= f.text_area :body, class: "form-control wysihtml5" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit "Save", class: "btn btn-default" %>
        </div>
      </div>
    </fieldset>
<% end %>

app/views/pages/show.html.erb
<div class="page-container">
  <div class="page-header"><h2><%= @page.title %></h2></div>
  <div class="page-body"><%= @page.body.html_safe %></div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rails WebBlog Platform", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Articles
            <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "List all", articles_path %></li>
            <li><%= link_to "New", controller: :articles, action: :new %></li>
          </ul>
        </li>
        <% Page.all.each do |page| %>
        <li><%= link_to page.name, page %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><a href="#">Logged as: <%= current_user.name %></a></li>
            <% if is_admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage Pages
                    <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "New page", controller: 'pages', action: 'new' %></li>
                    <li><%= link_to "Manage pages", controller: 'pages', action: 'index' %></li>
                  </ul>
                </li>
            <%end%>
            <li><%= link_to "Log out", '/logout' %></li>
        <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Register", controller: 'users', action: 'new' %></li>
                <li><%= link_to "Log in", controller: 'sessions', action: 'new' %></li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<form class="form-horizontal col-lg-6 col-lg-offset-3" method="post" >
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
	<fieldset>
		<legend>Sign Up form</legend>
		<div class="form-group">
			<label for="inputEmail" class="col-lg-2 control-label">Email </label>
			<div class="col-lg-10">
				<%= text_field(:user, :email, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<label for="inputEmail" class="col-lg-2 control-label">Username </label>
			<div class="col-lg-10">
				<%= text_field(:user, :name, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<label for="inputPassword" class="col-lg-2 control-label">Password </label>
			<div class="col-lg-10">
				<%= password_field(:user, :password, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<label for="inputPassword" class="col-lg-2 control-label">Confirm Password </label>
			<div class="col-lg-10">
				<%= password_field(:user, :password_confirmation, class: "form-control") %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-10 col-lg-offset-2">
				<button type="submit" class="btn btn-primary">Submit</button>
			</div>
		</div>
	</fieldset>
</form>